# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:chainguard-dev/malcontent-action:.*
claim_pattern:
  job_workflow_ref: chainguard-dev/malcontent-action/.github/workflows/blockpr.yaml@.*

permissions:
  contents: write
  pull_requests: write
  workflows: write
