name: blockpr

on:
  pull_request:
    branches:
      - main
      - blockpr

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0
        with:
          egress-policy: audit
      
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
        id: octo-sts
        with:
          scope: chainguard-dev/malcontent-action
          identity: blockpr
      
      - name: Prepare before/after directories
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          mkdir before after
          git --work-tree=before checkout origin/${{ github.event.pull_request.base.ref }} -- .
          git --work-tree=after checkout HEAD -- .
      
      - name: Run malware scan diff (base branch vs PR head)
        id: malcontent
        uses: ./
        with:
          malcontent-image: "cgr.dev/chainguard/malcontent@sha256:fdfca44c401a5ca98af51292a821278644895bc1963f7a76a733d76647ff0ede"
          before-dir: ${{ github.workspace }}/before
          after-dir: ${{ github.workspace }}/after
          exit-code: 0
    
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 #v3.29.0 - 11 Jun 2025
        with:
          sarif_file: ${{ steps.malcontent.outputs.diff-sarif }}
          category: malcontent
    
      - name: Upload Markdown diff report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2 - 19 March 2025
        with:
          name: malcontent-sarif
          path: ${{ steps.malcontent.outputs.diff-sarif }}
