name: malwaretest

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
      
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: chainguard-dev/malcontent-bot
          identity: malwaretest
      
      - name: Run malware test action on 8.3.41 folder diff
        uses: ./.github/actions/malwaretest
        with:
          malcontent-image: "cgr.dev/chainguard/malcontent@sha256:fdfca44c401a5ca98af51292a821278644895bc1963f7a76a733d76647ff0ede"
        env:
          BEFORE_DIR: ${{ github.workspace }}/samples-base/python/2024.ultralytics/8.3.41
          AFTER_DIR: ${{ github.workspace }}/python/2024.ultralytics/8.3.41
