name: malwaretest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0
        with:
          egress-policy: audit
      
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
        id: octo-sts
        with:
          scope: chainguard-dev/malcontent-action
          identity: malwaretest
      
      - name: Initialize CodeQL (optional, for SARIF analysis)
        uses: github/codeql-action/init@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 #v3.29.0 - 11 Jun 2025
        with:
          config: |
            paths-ignore:
              - testfiles/**
      
      - name: Run malware test action on 8.3.40 → 8.3.41 diff
        id: malcontent
        uses: ./
        with:
          malcontent-image: "cgr.dev/chainguard/malcontent@sha256:fdfca44c401a5ca98af51292a821278644895bc1963f7a76a733d76647ff0ede"
          before-dir: ${{ github.workspace }}/testfiles/malcontent-samples/python/2024.ultralytics/v8.3.40
          after-dir: ${{ github.workspace }}/testfiles/malcontent-samples/python/2024.ultralytics/v8.3.41
          exit-code: 0

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858 #v3.29.0 - 11 Jun 2025
        with:
          sarif_file: ${{ steps.malcontent.outputs.diff-sarif }}
          category: malcontent
